- name: Initialize Kubernetes
  command: kubeadm init --pod-network-cidr=192.168.0.0/16
  args:
    creates: /etc/kubernetes/admin.conf

- name: Create kube dir
  file:
    path: /root/.kube
    state: directory

- name: Copy admin.conf
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: yes

- name: Install Calico
  command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command

- name: Share join command with other hosts
  set_fact:
    kube_join_command: "{{ join_command.stdout }}"

# - name: copy file
#   copy:
#     src: files/*
#     dest: /opt/guacamole_manifest/
#     mode: '0644'
  