#cloud-config
packages:
  - ifupdown
package_update: true
#package_upgrade: true
#cloud-config
packages:
  - ifupdown
package_update: true
package_upgrade: true

write_files:
  - path: /etc/systemd/network/10-enp7s0.network
    content: |
      # Custom network configuration added by cloud-init
      [Match]
      Name=enp7s0

      [Network]
      DHCP=yes
      Gateway=${gateway_ip}
    append: true

  - path: /etc/systemd/resolved.conf
    content: |
      [Resolve]
      DNS=185.12.64.2 185.12.64.1
      FallbackDNS=8.8.8.8
    append: true

runcmd:
  #- |
  #  cat <<'EOF' >> /etc/systemd/network/10-enp7s0.network
  #  [Match]
  #  Name=enp7s0
  #  
  #  [Network]
  #  DHCP=yes
  #  #Gateway=10.0.0.1
  #  Gateway=${gateway_ip}
  #  EOF
  #  sudo sed -i 's/^#DNS=/DNS=8.8.8.8/' /etc/systemd/resolved.conf
  - apt remove -y hc-utils
  - reboot