---
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: restart prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted

- name: restart alertmanager
  ansible.builtin.systemd:
    name: alertmanager
    state: restarted

- name: restart autoscaler
  ansible.builtin.systemd:
    name: autoscaler
    state: restarted
