---
- name: Create KDE user
  user:
    name: "{{ kde_user }}"
    shell: /bin/bash
    groups: sudo
    append: true
    password: "{{ kde_password_plain | password_hash('sha512') }}"
    state: present
  when: KDE | bool

- name: Configure xRDP to start KDE (Inline)
  ansible.builtin.copy:
    content: "exec startplasma-x11\n"
    dest: "/home/{{ kde_user }}/.xsession"
    owner: "{{ kde_user }}"
    group: "{{ kde_user }}"
    mode: "0644"
  when: KDE | bool

- name: Add KDE user to ssl-cert group
  user:
    name: "{{ kde_user }}"
    groups: ssl-cert
    append: true
  when: KDE | bool

- name: Restart xRDP
  systemd:
    name: xrdp
    state: restarted
  when: KDE | bool
