- name: Check if node is already part of the cluster
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: k8s_initialized

- name: Join Kubernetes cluster
  command: "{{ hostvars[groups['k8s_master_servers'][0]].kube_join_command }}"
  when: not k8s_initialized.stat.exists
