---
- name: "VNC Setup for VMID {{ current_vmid }}"
  block:
    - name: "Set deterministic VNC display + TCP port for VMID {{ current_vmid }}"
      set_fact:
        vnc_port: "{{ current_vmid | int - 200 }}"
        firewall_port: "{{ 5900 + current_vmid | int - 200 }}"


    - name: "Display chosen VNC port for VMID {{ current_vmid }}"
      debug:
        msg: "Using VNC display :{{ vnc_port }} (TCP {{ firewall_port }}) for VM {{ current_vmid }}"

    - name: "Apply VNC args on VM {{ current_vmid }}"
      command: >
        qm set {{ current_vmid | int }} -args "-vnc 0.0.0.0:{{ vnc_port }}"

    - name: "Allow VNC port through firewall for VMID {{ current_vmid }}"
      ansible.builtin.iptables:
        chain: INPUT
        protocol: tcp
        destination_port: "{{ firewall_port }}"
        jump: ACCEPT
        state: present
        ip_version: ipv4
      become: true

    - name: "Restart VM {{ current_vmid }} to apply VNC changes"
      shell: "qm stop {{ current_vmid | int }} && qm start {{ current_vmid | int }}"
      ignore_errors: true  # In case VM is already stopped
