[Service]
ExecStart=
ExecStart=/usr/bin/prometheus \
  --config.file=/opt/infra/prometheus/config/prometheus.yml \
  --storage.tsdb.path=/var/lib/prometheus/data \
  --web.console.libraries=/usr/share/prometheus/console_libraries \
  --web.console.templates=/usr/share/prometheus/consoles
