#cloud-config

package_update: true
packages:
  - nginx
  - networkd-dispatcher

write_files:
  - path: /etc/networkd-dispatcher/routable.d/10-eth0-post-up
    content: |
      #!/bin/bash
      
      echo 1 > /proc/sys/net/ipv4/ip_forward
      iptables -t nat -A POSTROUTING -s '10.20.0.0/24' -o eth0 -j MASQUERADE
    permissions: '0755'

runcmd:
  - reboot