#cloud-config

package_update: true
packages:
  - nginx
  - networkd-dispatcher

write_files:
  - path: /etc/networkd-dispatcher/routable.d/10-eth0-post-up
    content: |
      #!/bin/bash
      
      echo 1 > /proc/sys/net/ipv4/ip_forward
      iptables -t nat -A POSTROUTING -s '${private_network_cidr}' -o eth0 -j MASQUERADE
    permissions: '0755'

  # NGINX auto-config script
  - path: /usr/local/bin/configure-nginx-public-ip.sh
    owner: root:root
    permissions: '0755'
    content: |
      #!/usr/bin/env bash
      set -euo pipefail

      PUBLIC_IP=$(curl -s http://169.254.169.254/metadata/v1/public-ipv4 || true)

      if [ -z "$PUBLIC_IP" ]; then
        echo "Could not get public IP from metadata." >&2
        exit 1
      fi

      cat >/etc/nginx/sites-available/guacamole <<EOF
      server {
        listen 80;
        server_name $${PUBLIC_IP};
            location /xyz123xyz456 {
        return 302 "http://guacamole.playsoft.io/#/?token=C6F220976578A083CD25E3121111045D90598B323878F1F26EC176E7A88AD70D";
        }
        
        location /guacamole/ {
          proxy_pass http://10.20.0.10:30080/guacamole/;
          proxy_http_version 1.1;

          proxy_set_header Upgrade \$http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_set_header Host \$host;
          proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto \$scheme;
        }
      }
      EOF

      rm -f /etc/nginx/sites-enabled/default
      ln -sf /etc/nginx/sites-available/guacamole /etc/nginx/sites-enabled/guacamole

      nginx -t
      systemctl restart nginx

runcmd:
  - /usr/local/bin/configure-nginx-public-ip.sh
  - reboot