---
# Variables for the [proxmox] group
start_vnc_port: "{{ (vnc_base_port | int - 5900) + 1 }}"
max_vnc_port: "{{ (vnc_base_port | int - 5900) + 100 }}"
node_name: playsoft-proxmox
tf_output_path: "~/playsoft-jilani-gharbi/playsoft-infra/terraform-k8s/tf_output.json"
  