---
# Path to root Terraform output JSON (contains edge_public_ip)
tf_output_path_root: "~/playsoft-jilani-gharbi/playsoft-infra/terraform/tf_output.json"

# Path to Proxmox Terraform output JSON (contains vm_ids)
tf_output_path_proxmox: "~/playsoft-jilani-gharbi/playsoft-infra/terraform/modules/vnc-server/tf_output.json"

# Template config — same defaults as guacamole_connection role
user_prefix: "candidat"
user_password_prefix: "candidat"
guacamole_users: []
