#!/bin/bash
set -euo pipefail

# -----------------------------
#          CONFIG
# -----------------------------
HCLOUD_TOKEN=${HCLOUD_TOKEN:? "❌ ERROR: HCLOUD_TOKEN is not set!"}

SSH_KEY_NAME="${SSH_KEY_NAME:-jilani-key}"
MY_IP="${MY_IP:-0.0.0.0/0}"

TFVARS_FILE="${TFVARS_FILE:-env/dev.tfvars}"
PKR_VARS_FILE="${PKR_VARS_FILE:-dev.pkrvars.hcl}"

# Base paths
BASE=~/playsoft-jilani-gharbi/playsoft-infra
TF_HETZNER_DIR="$BASE/terraform"
TF_PROXMOX_DIR="$BASE/terraform/modules/vnc-server"
ANSIBLE_DIR="$BASE/ansible"

# SSH config generated by Terraform (if you followed earlier advice)
SSH_INCLUDE_FILE="${SSH_INCLUDE_FILE:-$HOME/.ssh/config}"
# Host aliases used in SSH config
BASTION_HOST_ALIAS="${BASTION_HOST_ALIAS:-bastion}"
GUAC_HOST_ALIAS="${GUAC_HOST_ALIAS:-guacamole}"

# Colors
green() { printf "\033[0;32m%s\033[0m\n" "$*"; }
yellow() { printf "\033[0;33m%s\033[0m\n" "$*"; }
red() { printf "\033[0;31m%s\033[0m\n" "$*"; }

echo "🧹 Starting CLEANUP (reverse of deployment) ..."
echo "-----------------------------------------------"

# -----------------------------
# 0) Stop guacamole port-forward
# -----------------------------
yellow "🛑 Stopping any kubectl port-forward running on '${GUAC_HOST_ALIAS}'..."
set +e
ssh -o BatchMode=yes -o StrictHostKeyChecking=accept-new "${GUAC_HOST_ALIAS}" "pkill -f 'kubectl port-forward' " >/dev/null 2>&1
PF_KILLED=$?
set -e
if [ $PF_KILLED -eq 0 ]; then
  green "✅ Port-forward process stopped."
else
  yellow "ℹ️ No port-forward process to stop (or SSH not available)."
fi
# -----------------------------
# 1) Terraform destroy (Proxmox)
# -----------------------------
if [ -d "$TF_PROXMOX_DIR" ]; then
  yellow "🔥 Destroying Proxmox VMs via Terraform..."
  cd "$TF_PROXMOX_DIR"
  # Init if needed
  terraform init -input=false -upgrade=false >/dev/null 2>&1 || true
  terraform destroy -auto-approve || yellow "⚠️ Proxmox destroy encountered warnings."
  green "✅ Proxmox resources destroyed."
else
  yellow "ℹ️ Proxmox Terraform dir not found: $TF_PROXMOX_DIR (skipping)."
fi

# -----------------------------
# 2) Terraform destroy (Hetzner)
# -----------------------------
if [ -d "$TF_HETZNER_DIR" ]; then
  yellow "🔥 Destroying Hetzner Cloud resources via Terraform..."
  cd "$TF_HETZNER_DIR"
  # Init if needed
  terraform init -input=false -upgrade=false >/dev/null 2>&1 || true

  terraform destroy \
    -var="ssh_key_name=$SSH_KEY_NAME" \
    -var="my_ip=$MY_IP" \
    -var-file="$TFVARS_FILE" \
    -auto-approve

  green "✅ Hetzner resources destroyed."
else
  yellow "ℹ️ Hetzner Terraform dir not found: $TF_HETZNER_DIR (skipping)."
fi

# -----------------------------
# 3) Remove Terraform outputs
# -----------------------------
if [ -f "$TF_HETZNER_DIR/tf_output.json" ]; then
  rm -f "$TF_HETZNER_DIR/tf_output.json"
  yellow "🗑 Removed $TF_HETZNER_DIR/tf_output.json"
fi
if [ -f "$TF_PROXMOX_DIR/tf_output.json" ]; then
  rm -f "$TF_PROXMOX_DIR/tf_output.json"
  yellow "🗑 Removed $TF_PROXMOX_DIR/tf_output.json"
fi

# -----------------------------
# 4) Optional: cleanup SSH artifacts
# -----------------------------
# Remove terraform-managed SSH include file
if [ -f "$SSH_INCLUDE_FILE" ]; then
  yellow "🗑 Removing Terraform-generated SSH include file: $SSH_INCLUDE_FILE"
  rm -f "$SSH_INCLUDE_FILE"
fi

# Optionally remove known_hosts entries (safe if hosts will be re-created with new keys)
if command -v ssh-keygen >/dev/null 2>&1; then
  yellow "🧽 Cleaning known_hosts for '${BASTION_HOST_ALIAS}' and '${GUAC_HOST_ALIAS}' (optional)..."
  ssh-keygen -f '/home/jilani/.ssh/known_hosts' -R "$BASTION_HOST_ALIAS"
  ssh-keygen -f '/home/jilani/.ssh/known_hosts' -R "$GUAC_HOST_ALIAS"
fi

# -----------------------------
# 6) Snapshot/image cleanup (manual or API)
# -----------------------------
yellow "ℹ️ If Packer created images/snapshots in Hetzner, delete them via the Hetzner UI or provide names to auto-delete via API."

echo
green "🎉 CLEANUP COMPLETE"
