#!/bin/bash
# Auto-generates ansible/inventory.ini from terraform-k8s/tf_output.json.
# Handles any number of masters and workers.

set -e

PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TF_OUTPUT="${PROJECT_ROOT}/terraform-k8s/tf_output.json"
INVENTORY="${PROJECT_ROOT}/ansible/inventory.ini"

if [ ! -f "${TF_OUTPUT}" ]; then
  echo "❌ ERROR: ${TF_OUTPUT} not found. Run 'terraform output -json > tf_output.json' first."
  exit 1
fi

BASTION_IP=$(jq -r '.bastion_public_ip.value' "${TF_OUTPUT}")
MONITORING_IP=$(jq -r '.monitoring_public_ip.value' "${TF_OUTPUT}")
MASTER_COUNT=$(jq -r '.k8s_master_private_ips.value | length' "${TF_OUTPUT}")
WORKER_COUNT=$(jq -r '.k8s_worker_private_ips.value | length' "${TF_OUTPUT}")

{
  echo "# AUTO-GENERATED — do not edit manually."
  echo "# Re-generated by scripts/generate_inventory.sh from tf_output.json on every deploy."
  echo ""
  echo "[bastion]"
  echo "bastion ansible_host=${BASTION_IP} ansible_user=root ansible_ssh_private_key_file=/home/jilani/.ssh/jilani"
  echo ""
  echo "[bastion:vars]"
  echo "ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'"
  echo ""
  echo "[monitoring]"
  echo "monitoring ansible_host=${MONITORING_IP} ansible_user=root ansible_ssh_private_key_file=/home/jilani/.ssh/jilani"
  echo ""
  echo "[monitoring:vars]"
  echo "ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'"
  echo ""
  echo "[proxmox]"
  echo "playsoft-proxmox ansible_host=<PROXMOX_HOST> ansible_user=<SERVER_USER> ansible_ssh_private_key_file=/home/jilani/.ssh/jilani"
  echo ""
  echo "[k8s_master_servers]"
  for i in $(seq 0 $((MASTER_COUNT - 1))); do
    IP=$(jq -r ".k8s_master_private_ips.value[${i}]" "${TF_OUTPUT}")
    echo "k8s-master-$((i + 1)) ansible_host=${IP} ansible_ssh_private_key_file=/home/jilani/.ssh/jilani"
  done
  echo ""
  echo "[k8s_workers]"
  for i in $(seq 0 $((WORKER_COUNT - 1))); do
    IP=$(jq -r ".k8s_worker_private_ips.value[${i}]" "${TF_OUTPUT}")
    echo "k8s-worker-$((i + 1)) ansible_host=${IP} ansible_ssh_private_key_file=/home/jilani/.ssh/jilani"
  done
  echo ""
  echo "[k8s_nodes:children]"
  echo "k8s_master_servers"
  echo "k8s_workers"
  echo ""
  echo "[k8s_nodes:vars]"
  echo "ansible_user=root"
  echo "ansible_ssh_common_args='-o ProxyCommand=\"ssh -i /home/jilani/.ssh/jilani -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -l root ${BASTION_IP} -W %h:%p\"'"
} > "${INVENTORY}"

echo "Inventory generated: ${MASTER_COUNT} master(s), ${WORKER_COUNT} worker(s), bastion=${BASTION_IP}, monitoring=${MONITORING_IP}"
