#!/bin/bash
# Auto-generates ansible-amazon/inventory.ini from terrafrom-amazone/tf_output.json.
# Handles any number of masters and workers (worker ASG can scale between
# worker_min_size/worker_max_size in env/dev.tfvars).
#
# Static counterpart to ansible-amazon/inventory/aws_ec2.yml (the
# amazon.aws.aws_ec2 dynamic inventory plugin) -- unlike that plugin, this
# has to be re-run manually after every apply/scaling event to pick up
# instance replacements, same tradeoff as the Hetzner project's
# scripts/generate_inventory.sh.
#
# ansible_user, ansible_ssh_private_key_file and the bastion ProxyCommand
# are NOT written here -- ansible-amazon/group_vars/all.yml and
# group_vars/k8s_nodes.yml already supply those for any inventory source,
# static or dynamic, so this file only needs to carry per-host ansible_host.

set -e

PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TF_OUTPUT="${PROJECT_ROOT}/terrafrom-amazone/tf_output.json"
INVENTORY="${PROJECT_ROOT}/ansible-amazon/inventory.ini"

if [ ! -f "${TF_OUTPUT}" ]; then
  echo "❌ ERROR: ${TF_OUTPUT} not found. Run 'terraform output -json > tf_output.json' first (inside terrafrom-amazone/)."
  exit 1
fi

BASTION_IP=$(jq -r '.bastion_public_ip.value' "${TF_OUTPUT}")
MASTER_COUNT=$(jq -r '.master_private_ips.value | length' "${TF_OUTPUT}")
WORKER_COUNT=$(jq -r '.worker_private_ips.value | length' "${TF_OUTPUT}")

{
  echo "# AUTO-GENERATED — do not edit manually."
  echo "# Re-generated by scripts/generate_inventory_aws.sh from terrafrom-amazone/tf_output.json on every deploy."
  echo ""
  echo "[bastion]"
  echo "bastion ansible_host=${BASTION_IP}"
  echo ""
  echo "[k8s_master_servers]"
  for i in $(seq 0 $((MASTER_COUNT - 1))); do
    IP=$(jq -r ".master_private_ips.value[${i}]" "${TF_OUTPUT}")
    echo "k8s-master-$((i + 1)) ansible_host=${IP}"
  done
  echo ""
  echo "[k8s_workers]"
  for i in $(seq 0 $((WORKER_COUNT - 1))); do
    IP=$(jq -r ".worker_private_ips.value[${i}]" "${TF_OUTPUT}")
    echo "k8s-worker-$((i + 1)) ansible_host=${IP}"
  done
  echo ""
  echo "[k8s_nodes:children]"
  echo "k8s_master_servers"
  echo "k8s_workers"
} > "${INVENTORY}"

echo "Inventory generated: ${MASTER_COUNT} master(s), ${WORKER_COUNT} worker(s), bastion=${BASTION_IP}"
