[Service]
ExecStart=
ExecStart=/usr/bin/prometheus \
  --config.file=/opt/infra/prometheus/config/prometheus.yml \
  --storage.tsdb.path=/var/lib/prometheus/data \
  --web.listen-address=0.0.0.0:9090 \
  --web.enable-lifecycle
