- name: Add a guacamole connection and user
  hosts: localhost
  become: false

  vars_files:
    - vars.yml

  tasks:
    - name: Load Terraform output
      set_fact:
        tf: "{{ lookup('file', '~/playsoft-jilani-gharbi/playsoft-infra/terraform/tf_output.json') | from_json }}"

    - name: Add a new VNC connection
      scicore.guacamole.guacamole_connection:
        base_url: "http://{{ tf.edge_public_ip.value }}"
        auth_username: "{{ auth_username }}"
        auth_password: "{{ auth_password }}"
        connection_name: "{{ connection_name }}"
        protocol: "{{ protocol }}"
        hostname: "{{ hostname }}"
        port: "{{ port }}"
      register: _connection_info

    - debug:
        var: _connection_info

    - name: Add a new guacamole user
      scicore.guacamole.guacamole_user:
        base_url: "http://{{ tf.edge_public_ip.value }}"
        auth_username: "{{ auth_username }}"
        auth_password: "{{ auth_password }}"
        username: "{{ user_username }}"
        password: "{{ user_password }}"
        full_name: "{{ user_full_name }}"
        email: "{{ user_email }}"
        organization: "{{ user_organization }}"
        allowed_connections:
          - "{{ connection_name }}"
      register: _user_info

    - debug:
        var: _user_info